### ISSUE TITLE
Write copy about election day polling places

### ISSUE THREAD

**Issue by mapsandapps** [codeforatlanta/early-voting#47]
It's been brought to my attention that several people will show up to an early voting location on election day. If you want to vote on election day, you need to go to your regular polling place, not any early voting one.

Please write some copy to add to the site to clarify this point. For now, this should point them to the Secretary of State "My Voter Page" to find their polling place. https://www.mvp.sos.ga.gov/MVP/mvp.do

**Comment by Rummy222** [comment]
ON ELECTION DAY do not go to an ‘Early Voting’ location.  Early Voting locations are only to be used  before the designated election day.

**Comment by mapsandapps** [comment]
Hi, @Rummy222 👋 

I probably edited this while you were looking at it. Could you add some text about the My Voter Page? Thanks!

**Comment by Rummy222** [comment]
Sure…do you want an explanation of what it is, or instructions on how to use it?

**Comment by mapsandapps** [comment]
@Rummy222 Nothing too detailed. Basically the idea is to let them know how they can find their normal polling location, if they don't already know where it is.

**Comment by Rummy222** [comment]
If you are going to vote on the day of the election,  instead of voting early, go to this page – My Voter Page.
On this page you can fill in your Name and Birth Date and it will tell you where to go to vote on the day of the election.
If you are voting early, you will go to a different place to vote then if you are going to vote on the day-of the election.

**Comment by mapsandapps** [comment]
@Rummy222 Sounds good to me! Thanks for helping out. I'll assign this ticket to me for integration of this copy into the UI.
